production:
  solr:
    hostname: localhost
    port: 8983
    log_level: WARNING

development:
  solr:
    hostname: 0.0.0.0
    port: 8982
    log_level: WARNING

test:
  solr:
    hostname: localhost
    port: 8982
    log_level: WARNING
    